version: "3.8"

services:
  minio:
    image: minio/minio:latest
    ports:
      - "${MINIO_PORT:-9000}:9000"
      - "${UI_MINIO_PORT:-9001}:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped

  file_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MINIO_BASE_URL=${MINIO_BASE_URL:-minio}
      - MINIO_PORT=${MINIO_PORT:-9000}
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minioadmin}
      - MINIO_USE_SSL=${MINIO_USE_SSL:-false}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME:-images-bucket}
      - SERVICE_UPLOAD_LIMIT=${SERVICE_UPLOAD_LIMIT:-10}
      - SERVICE_DOWNLOAD_LIMIT=${SERVICE_DOWNLOAD_LIMIT:-10}
      - SERVICE_LIST_LIMIT=${SERVICE_LIST_LIMIT:-100}
      - SERVICE_CHUNK_SIZE=${SERVICE_CHUNK_SIZE:-1048576}
      - SERVER_ADDR=${SERVER_ADDR:-0.0.0.0:8000}
    depends_on:
      - minio
    restart: unless-stopped

volumes:
  minio_data:
